/* Sergio Escalona y Kevin Rojas*/
package Vista;

import Controlador.Registro;
import Modelo.Articulo;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;

/**
 *
 * @author CASA
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoAgregar = new javax.swing.ButtonGroup();
        GrupoModificar = new javax.swing.ButtonGroup();
        Pestañas = new javax.swing.JTabbedPane();
        PanelAgregar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AgregarCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AgregarDescripcion = new javax.swing.JTextField();
        AgregarDetalle = new javax.swing.JRadioButton();
        AgregarBueno = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AgregarRestaurado = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        AgregarPrecio = new javax.swing.JTextField();
        AgregarLocal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BotonAgregar = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        PanelListar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ListarCodigo = new javax.swing.JTextField();
        BotonListarArt = new javax.swing.JButton();
        BotonListarTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLista = new javax.swing.JTable();
        PanelEliminar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EliminarCodigo = new javax.swing.JTextField();
        BotonEliminar = new javax.swing.JButton();
        PanelModificar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ModificarCodigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ModificarDescripcion = new javax.swing.JTextField();
        ModificarPrecio = new javax.swing.JTextField();
        ModificarLocal = new javax.swing.JTextField();
        ModificarBueno = new javax.swing.JRadioButton();
        ModificarDetalle = new javax.swing.JRadioButton();
        ModificarRestaurado = new javax.swing.JCheckBox();
        BotonBuscar = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        PanelSalir = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Agregar Artículo");

        jLabel2.setText("Código");

        jLabel3.setText("Descripción");

        GrupoAgregar.add(AgregarDetalle);
        AgregarDetalle.setText("Con Detalles");

        GrupoAgregar.add(AgregarBueno);
        AgregarBueno.setText("Bueno");

        jLabel4.setText("Estado");

        jLabel5.setText("Restaurado");

        jLabel6.setText("Precio");

        jLabel7.setText("Local Venta");

        BotonAgregar.setText("Agregar");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAgregarLayout = new javax.swing.GroupLayout(PanelAgregar);
        PanelAgregar.setLayout(PanelAgregarLayout);
        PanelAgregarLayout.setHorizontalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelAgregarLayout.createSequentialGroup()
                                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgregarRestaurado)
                                    .addComponent(AgregarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelAgregarLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                                        .addComponent(BotonAgregar)
                                        .addGap(42, 42, 42)
                                        .addComponent(BotonLimpiar))
                                    .addComponent(AgregarLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(AgregarBueno)
                                .addGap(8, 8, 8)
                                .addComponent(AgregarDetalle))
                            .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(AgregarCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(AgregarDescripcion, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        PanelAgregarLayout.setVerticalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AgregarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AgregarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AgregarBueno)
                    .addComponent(AgregarDetalle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarRestaurado)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(AgregarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AgregarLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregar)
                    .addComponent(BotonLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pestañas.addTab("Agregar", PanelAgregar);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Listar Artículos");

        jLabel9.setText("Código");

        BotonListarArt.setText("Listar Artículo");
        BotonListarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarArtActionPerformed(evt);
            }
        });

        BotonListarTodo.setText("Listar Todo");
        BotonListarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarTodoActionPerformed(evt);
            }
        });

        TablaLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Estado", "Restaurado", "Precio", "Sucursal"
            }
        ));
        jScrollPane1.setViewportView(TablaLista);

        javax.swing.GroupLayout PanelListarLayout = new javax.swing.GroupLayout(PanelListar);
        PanelListar.setLayout(PanelListarLayout);
        PanelListarLayout.setHorizontalGroup(
            PanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .addGroup(PanelListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(ListarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(PanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(PanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BotonListarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonListarArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelListarLayout.setVerticalGroup(
            PanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(PanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ListarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonListarArt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonListarTodo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
        );

        Pestañas.addTab("Listar", PanelListar);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Eliminar Artículo");

        jLabel11.setText("Código");

        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEliminarLayout = new javax.swing.GroupLayout(PanelEliminar);
        PanelEliminar.setLayout(PanelEliminarLayout);
        PanelEliminarLayout.setHorizontalGroup(
            PanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEliminarLayout.createSequentialGroup()
                .addGroup(PanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEliminarLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel10))
                    .addGroup(PanelEliminarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEliminarLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(BotonEliminar)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        PanelEliminarLayout.setVerticalGroup(
            PanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(33, 33, 33)
                .addGroup(PanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(EliminarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(BotonEliminar)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        Pestañas.addTab("Eliminar", PanelEliminar);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Modificar Artículo");

        jLabel13.setText("Código");

        jLabel14.setText("Descripción");

        jLabel15.setText("Estado");

        jLabel16.setText("Restaurado");

        jLabel17.setText("Precio");

        jLabel18.setText("Local Venta");

        ModificarDescripcion.setEnabled(false);

        ModificarPrecio.setEnabled(false);

        ModificarLocal.setEnabled(false);

        GrupoModificar.add(ModificarBueno);
        ModificarBueno.setText("Bueno");
        ModificarBueno.setEnabled(false);

        GrupoModificar.add(ModificarDetalle);
        ModificarDetalle.setText("Con Detalle");
        ModificarDetalle.setEnabled(false);

        ModificarRestaurado.setEnabled(false);

        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        BotonModificar.setText("Modificar");
        BotonModificar.setEnabled(false);
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelModificarLayout = new javax.swing.GroupLayout(PanelModificar);
        PanelModificar.setLayout(PanelModificarLayout);
        PanelModificarLayout.setHorizontalGroup(
            PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificarLayout.createSequentialGroup()
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel12))
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelModificarLayout.createSequentialGroup()
                                .addComponent(ModificarBueno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ModificarDetalle))
                            .addGroup(PanelModificarLayout.createSequentialGroup()
                                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ModificarLocal)
                                    .addComponent(ModificarPrecio)
                                    .addComponent(ModificarDescripcion)
                                    .addComponent(ModificarCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                .addGap(44, 44, 44)
                                .addComponent(BotonBuscar))
                            .addComponent(ModificarRestaurado)))
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(BotonModificar)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        PanelModificarLayout.setVerticalGroup(
            PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ModificarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ModificarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ModificarBueno)
                    .addComponent(ModificarDetalle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModificarRestaurado)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ModificarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ModificarLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotonModificar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Pestañas.addTab("Modificar", PanelModificar);

        BotonSalir.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSalirLayout = new javax.swing.GroupLayout(PanelSalir);
        PanelSalir.setLayout(PanelSalirLayout);
        PanelSalirLayout.setHorizontalGroup(
            PanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSalirLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        PanelSalirLayout.setVerticalGroup(
            PanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSalirLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        Pestañas.addTab("Salir", PanelSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pestañas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pestañas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        int cod, pre;
        String des, est, res, loc;
        
        try {
            cod = Integer.parseInt(AgregarCodigo.getText());
            des = AgregarDescripcion.getText();
            if (AgregarBueno.isSelected())
                est = "Bueno";
            else
                est = "Con detalle";
            if (AgregarRestaurado.isSelected())
                res = "Si";
            else
                res = "No";
            pre = Integer.parseInt(AgregarPrecio.getText());
            loc = AgregarLocal.getText();
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error en el ingreso de datos", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Articulo art = new Articulo(cod, pre, des, est, res, loc);
        
        Registro rg = new Registro();
        if (rg.agregarArticulo(art))
            JOptionPane.showMessageDialog(this, "Se agregó artículo " + art.getCodigo(), "Información", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "No se agregó artículo " + art.getCodigo(), "Información", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        AgregarCodigo.setText("");
        AgregarDescripcion.setText("");
        GrupoAgregar.clearSelection();
        AgregarRestaurado.setSelected(false);
        AgregarPrecio.setText("");
        AgregarLocal.setText("");
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonListarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarArtActionPerformed
        int cod;
        try{
            cod = Integer.parseInt(ListarCodigo.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "El código solo debe contener números", "Validación", JOptionPane.WARNING_MESSAGE);
            ListarCodigo.requestFocus();
            return;
        }
        
        Registro rg = new Registro();
        DefaultTableModel tabla = (DefaultTableModel) TablaLista.getModel();
        
        tabla.setRowCount(0);
        Articulo art = rg.buscarArticulo(cod);
        
        if (art!=null)
            tabla.addRow(new Object []{art.getCodigo(), art.getDescripcion(), art.getEstado(), art.getRestaurado(), art.getPrecio(), art.getLocalventa()});
        else
            JOptionPane.showMessageDialog(this, "No se encontró código " + cod, "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BotonListarArtActionPerformed

    private void BotonListarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarTodoActionPerformed
        Registro rg = new Registro();
        DefaultTableModel tabla = (DefaultTableModel) TablaLista.getModel();
        
        tabla.setRowCount(0);
        ArrayList<Articulo> lista = rg.listarArticulo();
        
        for (Articulo art : lista)
            tabla.addRow(new Object []{art.getCodigo(), art.getDescripcion(), art.getEstado(), art.getRestaurado(), art.getPrecio(), art.getLocalventa()});
    }//GEN-LAST:event_BotonListarTodoActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        int cod;
        try{
            cod = Integer.parseInt(EliminarCodigo.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "El código solo debe contener números", "Validación", JOptionPane.WARNING_MESSAGE);
            EliminarCodigo.requestFocus();
            return;
        }
        
        Registro rg = new Registro();
        
        if (rg.eliminarArticulo(cod))
            JOptionPane.showMessageDialog(this, "Se eliminó artículo " + cod, "Información", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "No se eliminó artículo" + cod, "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        int cod;
        try{
            cod = Integer.parseInt(ModificarCodigo.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "El código solo debe contener números", "Validación", JOptionPane.WARNING_MESSAGE);
            ModificarCodigo.requestFocus();
            return;
        }
        
        Registro rg = new Registro();
        Articulo art = rg.buscarArticulo(cod);
        
        if (art!=null){
            ModificarCodigo.setEnabled(false);
            ModificarDescripcion.setEnabled(true);
            ModificarDescripcion.setText(art.getDescripcion());
            ModificarBueno.setEnabled(true);
            ModificarDetalle.setEnabled(true);
            if (art.getEstado().equals("Bueno"))
                ModificarBueno.setSelected(true);
            else
                ModificarDetalle.setSelected(true);
            ModificarRestaurado.setEnabled(true);
            if (art.getRestaurado().equals("Si"))
                ModificarRestaurado.setSelected(true);
            ModificarPrecio.setEnabled(true);
            ModificarPrecio.setText(String.valueOf(art.getPrecio()));
            ModificarLocal.setEnabled(true);
            ModificarLocal.setText(art.getLocalventa());
            BotonModificar.setEnabled(true);
        }
        else 
            JOptionPane.showMessageDialog(this, "No se encontró código " + cod, "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
        int cod, pre;
        String des, est, res, loc;
        
        cod = Integer.parseInt(ModificarCodigo.getText());
        try {
            des = ModificarDescripcion.getText();
            if (ModificarBueno.isSelected())
                est = "Bueno";
            else
                est = "Con detalle";
            if (ModificarRestaurado.isSelected())
                res = "Si";
            else
                res = "No";
            pre = Integer.parseInt(ModificarPrecio.getText());
            loc = ModificarLocal.getText();
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error en el ingreso de datos", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Articulo art = new Articulo(cod, pre, des, est, res, loc);
        
        Registro rg = new Registro();
        if (rg.modificarArticulo(art)){
            ModificarCodigo.setEnabled(true);
            ModificarDescripcion.setEnabled(false);
            ModificarDescripcion.setText("");
            ModificarBueno.setEnabled(false);
            ModificarDetalle.setEnabled(false);
            GrupoModificar.clearSelection();
            ModificarRestaurado.setEnabled(false);
            ModificarRestaurado.setSelected(false);
            ModificarPrecio.setEnabled(false);
            ModificarPrecio.setText("");
            ModificarLocal.setEnabled(false);
            ModificarLocal.setText("");
            BotonModificar.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Se modificó artículo " + cod, "Informació", JOptionPane.INFORMATION_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "No se modificó artículo " + cod, "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BotonModificarActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AgregarBueno;
    private javax.swing.JTextField AgregarCodigo;
    private javax.swing.JTextField AgregarDescripcion;
    private javax.swing.JRadioButton AgregarDetalle;
    private javax.swing.JTextField AgregarLocal;
    private javax.swing.JTextField AgregarPrecio;
    private javax.swing.JCheckBox AgregarRestaurado;
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonListarArt;
    private javax.swing.JButton BotonListarTodo;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JTextField EliminarCodigo;
    private javax.swing.ButtonGroup GrupoAgregar;
    private javax.swing.ButtonGroup GrupoModificar;
    private javax.swing.JTextField ListarCodigo;
    private javax.swing.JRadioButton ModificarBueno;
    private javax.swing.JTextField ModificarCodigo;
    private javax.swing.JTextField ModificarDescripcion;
    private javax.swing.JRadioButton ModificarDetalle;
    private javax.swing.JTextField ModificarLocal;
    private javax.swing.JTextField ModificarPrecio;
    private javax.swing.JCheckBox ModificarRestaurado;
    private javax.swing.JPanel PanelAgregar;
    private javax.swing.JPanel PanelEliminar;
    private javax.swing.JPanel PanelListar;
    private javax.swing.JPanel PanelModificar;
    private javax.swing.JPanel PanelSalir;
    private javax.swing.JTabbedPane Pestañas;
    private javax.swing.JTable TablaLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
